project:
  type: website

website:
  title: "Complete Guide to AI-SMPS"
  navbar:
    title: "AI-SMPS Guide"
    left:
      - text: "Home"
        href: "index.html"
      - text: "Introduction"
        href: "introduction.html"
      - text: "Uninformed Search"
        href: "uninformed.html"
