project:
  type: website

website:
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Index"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      - section: "Uninformed Search Algorithms"
        contents:
          - text: "Uninformed Search Overview"
            href: uninformed.qmd
          - text: "Breadth-First Search (BFS)"
            href: bfs.qmd
          - text: "Depth-First Search (DFS)"
            href: dfs.qmd
          - text: "Depth Limited Search (DLS)"
            href: dls.qmd
          - text: "Iterative Deepening DFS (IDDFS)"
            href: iddfs.qmd
          - text: "Uniform Cost Search (UCS)"
            href: ucs.qmd
      - section: "Informed Search Algorithms"

theme:
  light: litera
  dark: cyborg