project:
  type: website

# website:
#   navbar:
#     background: primary
#     search: true
#     left:
#       - text: "Index"
#         href: index.qmd
#       - text: "Introduction"
#         href: introduction.qmd
#       - text: "Uninformed"
#         href: uninformed.qmd

#   sidebar:
#     - title: "Uninformed Search Algorithms"
#       style: "docked"
#       background: light
#       contents:
#         - text: "Uninformed Search Overview"
#           href: uninformed.qmd
#         - text: "Breadth-First Search (BFS)"
#           href: bfs.qmd
#         - text: "Depth-First Search (DFS)"
#           href: dfs.qmd

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Index"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      - section: "Uninformed Search Algorithms"
        contents:
          - text: "Uninformed Search Overview"
            href: uninformed.qmd
          - text: "Breadth-First Search (BFS)"
            href: bfs.qmd
          - text: "Depth-First Search (DFS)"
            href: dfs.qmd
  